!==========================================================================================!
!==========================================================================================!
!     This subroutine will send the namelist information to the slave nodes.               !
!------------------------------------------------------------------------------------------!
subroutine masterput_ednl(mainnum)
   use ed_max_dims          , only : str_len                    & ! intent(in)
                                   , n_pft                      & ! intent(in)
                                   , maxpvars                   & ! intent(in)
                                   , nzgmax                     & ! intent(in)
                                   , str_len_short              & ! intent(in)
                                   , maxgrds                    & ! intent(in)
                                   , max_poi                    & ! intent(in)
                                   , max_ed_regions             & ! intent(in)
                                   , n_pft                      ! ! intent(in)
   use ed_misc_coms         , only : expnme                     & ! intent(in)
                                   , runtype                    & ! intent(in)
                                   , itimea                     & ! intent(in)
                                   , iyeara                     & ! intent(in)
                                   , imontha                    & ! intent(in)
                                   , idatea                     & ! intent(in)
                                   , itimez                     & ! intent(in)
                                   , iyearz                     & ! intent(in)
                                   , imonthz                    & ! intent(in)
                                   , idatez                     & ! intent(in)
                                   , dtlsm                      & ! intent(in)
                                   , radfrq                     & ! intent(in)
                                   , month_yrstep               & ! intent(in)
                                   , ifoutput                   & ! intent(in)
                                   , idoutput                   & ! intent(in)
                                   , imoutput                   & ! intent(in)
                                   , iqoutput                   & ! intent(in)
                                   , iooutput                   & ! intent(in)
                                   , iyoutput                   & ! intent(in)
                                   , itoutput                   & ! intent(in)
                                   , ndcycle                    & ! intent(in)
                                   , iclobber                   & ! intent(in)
                                   , obstime_db                 & ! intent(in)
                                   , frqfast                    & ! intent(in)
                                   , sfilin                     & ! intent(in)
                                   , ffilout                    & ! intent(in)
                                   , ied_init_mode              & ! intent(in)
                                   , thsums_database            & ! intent(in)
                                   , ivegt_dynamics             & ! intent(in)
                                   , ibigleaf                   & ! intent(in)
                                   , integration_scheme         & ! intent(in)
                                   , nsub_euler                 & ! intent(in)
                                   , end_time                   & ! intent(in)
                                   , current_time               & ! intent(in)
                                   , sfilout                    & ! intent(in)
                                   , frqstate                   & ! intent(in)
                                   , isoutput                   & ! intent(in)
                                   , iprintpolys                & ! intent(in)
                                   , printvars                  & ! intent(in)
                                   , npvars                     & ! intent(in)
                                   , pfmtstr                    & ! intent(in)
                                   , ipmin                      & ! intent(in)
                                   , ipmax                      & ! intent(in)
                                   , iedcnfgf                   & ! intent(in)
                                   , event_file                 & ! intent(in)
                                   , outfast                    & ! intent(in)
                                   , outstate                   & ! intent(in)
                                   , unitfast                   & ! intent(in)
                                   , unitstate                  & ! intent(in)
                                   , iadd_site_means            & ! intent(in)
                                   , iadd_patch_means           & ! intent(in)
                                   , iadd_cohort_means          & ! intent(in)
                                   , attach_metadata            & ! intent(in)
                                   , itimeh                     & ! intent(in)
                                   , iyearh                     & ! intent(in)
                                   , imonthh                    & ! intent(in)
                                   , idateh                     & ! intent(in)
                                   , iallom                     & ! intent(in)
                                   , economics_scheme           & ! intent(in)
                                   , igrass                     & ! intent(in)
                                   , min_site_area              & ! intent(in)
                                   , fast_diagnostics           & ! intent(in)
                                   , writing_dail               & ! intent(in)
                                   , writing_mont               & ! intent(in)
                                   , writing_dcyc               & ! intent(in)
                                   , writing_year               & ! intent(in)
                                   , writing_long               & ! intent(in) 
                                   , writing_eorq               & ! intent(in)
                                   , history_fast               & ! intent(in)
                                   , history_dail               & ! intent(in)
                                   , history_eorq               ! ! intent(in)
   use grid_coms            , only : nzg                        & ! intent(in)
                                   , nzs                        & ! intent(in)
                                   , ngrids                     & ! intent(in)
                                   , nnxp                       & ! intent(in)
                                   , nnyp                       & ! intent(in)
                                   , time                       & ! intent(in)
                                   , timmax                     ! ! intent(in)
   use soil_coms            , only : isoilflg                   & ! intent(in)
                                   , nslcon                     & ! intent(in)
                                   , isoilcol                   & ! intent(in)
                                   , slxclay                    & ! intent(in)
                                   , slxsand                    & ! intent(in)
                                   , slz                        & ! intent(in)
                                   , slmstr                     & ! intent(in)
                                   , stgoff                     & ! intent(in)
                                   , veg_database               & ! intent(in)
                                   , soil_database              & ! intent(in)
                                   , slcol_database             & ! intent(in)
                                   , soilstate_db               & ! intent(in)
                                   , soildepth_db               & ! intent(in)
                                   , isoilstateinit             & ! intent(in)
                                   , isoildepthflg              & ! intent(in)
                                   , isoilbc                    & ! intent(in)
                                   , sldrain                    & ! intent(in)
                                   , runoff_time                & ! intent(in)
                                   , zrough                     ! ! intent(in)
   use met_driver_coms      , only : lapse_scheme               & ! intent(in)
                                   , imetrad                    ! ! intent(in)
   use mem_polygons         , only : edres                      & ! intent(in)
                                   , maxsite                    & ! intent(in)
                                   , maxpatch                   & ! intent(in)
                                   , maxcohort                  ! ! intent(in)
   use physiology_coms      , only : iphysiol                   & ! intent(in)
                                   , h2o_plant_lim              & ! intent(in)
                                   , plant_hydro_scheme         & ! intent(in)
                                   , istomata_scheme            & ! intent(in)
                                   , istruct_growth_scheme      & ! intent(in)
                                   , istem_respiration_scheme   & ! intent(in)
                                   , trait_plasticity_scheme    & ! intent(in)
                                   , iddmort_scheme             & ! intent(in)
                                   , cbr_scheme                 & ! intent(in)
                                   , ddmort_const               & ! intent(in)
                                   , carbon_mortality_scheme    & ! intent(in)
                                   , hydraulic_mortality_scheme & ! intent(in)
                                   , n_plant_lim                & ! intent(in)
                                   , vmfact_c3                  & ! intent(in)
                                   , vmfact_c4                  & ! intent(in)
                                   , mphoto_trc3                & ! intent(in)
                                   , mphoto_tec3                & ! intent(in)
                                   , mphoto_c4                  & ! intent(in)
                                   , bphoto_blc3                & ! intent(in)
                                   , bphoto_nlc3                & ! intent(in)
                                   , bphoto_c4                  & ! intent(in)
                                   , kw_grass                   & ! intent(in)
                                   , kw_tree                    & ! intent(in)
                                   , gamma_c3                   & ! intent(in)
                                   , gamma_c4                   & ! intent(in)
                                   , d0_grass                   & ! intent(in)
                                   , d0_tree                    & ! intent(in)
                                   , alpha_c3                   & ! intent(in)
                                   , alpha_c4                   & ! intent(in)
                                   , klowco2in                  & ! intent(in)
                                   , rrffact                    & ! intent(in)
                                   , growthresp                 & ! intent(in)
                                   , quantum_efficiency_t       & ! intent(in)
                                   , q10_c3                     & ! intent(in)
                                   , q10_c4                     ! ! intent(in)
   use phenology_coms       , only : iphen_scheme               & ! intent(in)
                                   , repro_scheme               & ! intent(in)
                                   , iphenys1                   & ! intent(in)
                                   , iphenysf                   & ! intent(in)
                                   , iphenyf1                   & ! intent(in)
                                   , iphenyff                   & ! intent(in)
                                   , phenpath                   & ! intent(in)
                                   , radint                     & ! intent(in)
                                   , radslp                     & ! intent(in)
                                   , thetacrit                  ! ! intent(in)
   use decomp_coms          , only : n_decomp_lim               & ! intent(in)
                                   , decomp_scheme              ! ! intent(in)
   use pft_coms             , only : include_these_pft          & ! intent(in)
                                   , pasture_stock              & ! intent(in)
                                   , agri_stock                 & ! intent(in)
                                   , plantation_stock           & ! intent(in)
                                   , pft_1st_check              ! ! intent(in)
   use disturb_coms         , only : include_fire               & ! intent(in)
                                   , fire_parameter             & ! intent(in)
                                   , ianth_disturb              & ! intent(in)
                                   , sl_scale                   & ! intent(in)
                                   , sl_yr_first                & ! intent(in)
                                   , sl_nyrs                    & ! intent(in)
                                   , sl_pft                     & ! intent(in)
                                   , sl_prob_harvest            & ! intent(in)
                                   , sl_mindbh_harvest          & ! intent(in)
                                   , sl_biomass_harvest         & ! intent(in)
                                   , sl_skid_rel_area           & ! intent(in)
                                   , sl_skid_s_gtharv           & ! intent(in)
                                   , sl_skid_s_ltharv           & ! intent(in)
                                   , sl_felling_s_ltharv        & ! intent(in)
                                   , cl_fseeds_harvest          & ! intent(in)
                                   , cl_fstorage_harvest        & ! intent(in)
                                   , cl_fleaf_harvest           & ! intent(in)
                                   , lu_database                & ! intent(in)
                                   , plantation_file            & ! intent(in)
                                   , lu_rescale_file            & ! intent(in)
                                   , treefall_disturbance_rate  & ! intent(in)
                                   , time2canopy                & ! intent(in)
                                   , sm_fire                    & ! intent(in)
                                   , min_patch_area             ! ! intent(in)
   use optimiz_coms         , only : ioptinpt                   ! ! intent(in)
   use canopy_layer_coms    , only : crown_mod                  ! ! intent(in)
   use canopy_radiation_coms, only : icanrad                    & ! intent(in)
                                   , ihrzrad                    & ! intent(in)
                                   , ltrans_vis                 & ! intent(in)
                                   , ltrans_nir                 & ! intent(in)
                                   , lreflect_vis               & ! intent(in)
                                   , lreflect_nir               & ! intent(in)
                                   , orient_tree                & ! intent(in)
                                   , orient_grass               & ! intent(in)
                                   , clump_tree                 & ! intent(in)
                                   , clump_grass                ! ! intent(in)
   use rk4_coms             , only : rk4_tolerance              & ! intent(in)
                                   , ibranch_thermo             & ! intent(in)
                                   , ipercol                    ! ! intent(in)
   use canopy_air_coms      , only : icanturb                   & ! intent(in)
                                   , isfclyrm                   & ! intent(in)
                                   , ied_grndvap                & ! intent(in)
                                   , ubmin                      & ! intent(in)
                                   , ugbmin                     & ! intent(in)
                                   , ustmin                     & ! intent(in)
                                   , gamm                       & ! intent(in) 
                                   , gamh                       & ! intent(in) 
                                   , tprandtl                   & ! intent(in)
                                   , lwidth_grass               & ! intent(in)
                                   , lwidth_bltree              & ! intent(in)
                                   , lwidth_nltree              & ! intent(in)
                                   , ribmax                     & ! intent(in)
                                   , leaf_maxwhc                ! ! intent(in)
   use mem_edcp             , only : co2_offset                 ! ! intent(in)
   use detailed_coms        , only : dt_census                  & ! intent(in)
                                   , yr1st_census               & ! intent(in)
                                   , mon1st_census              & ! intent(in)
                                   , min_recruit_dbh            & ! intent(in)
                                   , idetailed                  & ! intent(in)
                                   , patch_keep                 ! ! intent(in)
   use fusion_fission_coms  , only : ifusion                    ! ! intent(in)
   implicit none
   !----- Standard common blocks. ---------------------------------------------------------!
#if defined(RAMS_MPI)
   include 'mpif.h'
#endif
   !----- Arguments. ----------------------------------------------------------------------!
   integer, intent(in) :: mainnum
   !----- Local variables. ----------------------------------------------------------------!
   integer             :: ierr
   integer             :: npv
   integer             :: ng
   !---------------------------------------------------------------------------------------!

#if defined(RAMS_MPI)
   call MPI_Bcast(time,1,MPI_DOUBLE_PRECISION,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(timmax,1,MPI_DOUBLE_PRECISION,mainnum,MPI_COMM_WORLD,ierr)

   call MPI_Bcast(current_time%year,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(current_time%month,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(current_time%date,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(current_time%time,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(current_time%ifirst,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)

   call MPI_Bcast(end_time%year,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(end_time%month,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(end_time%date,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(end_time%time,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(end_time%ifirst,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)

   call MPI_Bcast(dtlsm,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(month_yrstep,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ifoutput,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(idoutput,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(imoutput,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iqoutput,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iyoutput,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(itoutput,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iooutput,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(isoutput,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ndcycle,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iadd_site_means  ,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iadd_patch_means ,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iadd_cohort_means,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(attach_metadata,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(outfast,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(outstate,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(unitfast,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(unitstate,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ffilout,str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(sfilout,str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ied_init_mode,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(edres,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)

   do ng=1,maxgrds
      call MPI_Bcast(sfilin         (ng),str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)
      call MPI_Bcast(veg_database   (ng),str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)
      call MPI_Bcast(soil_database  (ng),str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)
      call MPI_Bcast(slcol_database (ng),str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)
      call MPI_Bcast(lu_database    (ng),str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)
      call MPI_Bcast(plantation_file(ng),str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)
      call MPI_Bcast(lu_rescale_file(ng),str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)
   end do

   call MPI_Bcast(thsums_database,str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(soilstate_db   ,str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(soildepth_db   ,str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(obstime_db     ,str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)

   call MPI_Bcast(isoilstateinit,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(isoildepthflg,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(isoilbc,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(sldrain,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ivegt_dynamics,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ibigleaf,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(integration_scheme,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(nsub_euler,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(rk4_tolerance,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ibranch_thermo,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iphysiol,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iallom,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(economics_scheme,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(igrass,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iphen_scheme,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(radint,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(radslp,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(repro_scheme,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(lapse_scheme,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(crown_mod,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(icanrad,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ihrzrad,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ltrans_vis,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ltrans_nir,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(lreflect_vis,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(lreflect_nir,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(orient_tree,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(orient_grass,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(clump_tree,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(clump_grass,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(decomp_scheme,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(h2o_plant_lim,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(plant_hydro_scheme,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(istomata_scheme,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(istruct_growth_scheme,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(istem_respiration_scheme,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(trait_plasticity_scheme,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iddmort_scheme,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(cbr_scheme,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ddmort_const,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(carbon_mortality_scheme,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(hydraulic_mortality_scheme,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(vmfact_c3,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(vmfact_c4,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(mphoto_trc3,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(mphoto_tec3,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(mphoto_c4,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(bphoto_blc3,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(bphoto_nlc3,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(bphoto_c4,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(kw_grass,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(kw_tree,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(gamma_c3,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(gamma_c4,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(d0_grass,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(d0_tree,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(alpha_c3,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(alpha_c4,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(klowco2in,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(rrffact,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(growthresp,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(lwidth_grass,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(lwidth_bltree,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(lwidth_nltree,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(q10_c3,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(q10_c4,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(thetacrit,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(quantum_efficiency_t,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(n_plant_lim,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(n_decomp_lim,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(include_fire,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(fire_parameter,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(sm_fire,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ianth_disturb,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(sl_scale           ,    1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(sl_yr_first        ,    1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(sl_nyrs            ,    1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(sl_pft             ,n_pft,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(sl_prob_harvest    ,n_pft,MPI_REAL   ,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(sl_mindbh_harvest  ,n_pft,MPI_REAL   ,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(sl_biomass_harvest ,    1,MPI_REAL   ,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(sl_skid_rel_area   ,    1,MPI_REAL   ,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(sl_skid_s_gtharv   ,    1,MPI_REAL   ,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(sl_skid_s_ltharv   ,    1,MPI_REAL   ,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(sl_felling_s_ltharv,    1,MPI_REAL   ,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(cl_fseeds_harvest  ,    1,MPI_REAL   ,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(cl_fstorage_harvest,    1,MPI_REAL   ,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(cl_fleaf_harvest   ,    1,MPI_REAL   ,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(icanturb,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ipercol,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(include_these_pft,n_pft,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(pasture_stock,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(agri_stock,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(plantation_stock,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(pft_1st_check,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ifusion,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(maxsite,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(maxpatch,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(maxcohort,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(min_site_area,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(min_patch_area,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(treefall_disturbance_rate,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(time2canopy,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(runoff_time,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iprintpolys,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(npvars,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   do npv=1,npvars
      call MPI_Bcast(printvars(npv),str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)
      call MPI_Bcast(pfmtstr(npv),str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)
   end do
   call MPI_Bcast(ipmin,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ipmax,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(imetrad ,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iphenys1,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iphenysf,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iphenyf1,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iphenyff,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iedcnfgf,str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(event_file,str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(phenpath,str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)

   !---------------------------------------------------------------------------------------!
   !      These are ED2 variables that have the same function as certain BRAMS namelist    !
   ! variables under a different name.                                                     !
   !---------------------------------------------------------------------------------------!
  
   call MPI_Bcast(frqfast,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(frqstate,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
  
   call MPI_Bcast(expnme,str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ngrids,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(runtype,str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(itimez,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(idatez,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(imonthz,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iyearz,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(itimeh,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(idateh,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(imonthh,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iyearh,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(itimea,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(idatea,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(imontha,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iyeara,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)

   call MPI_Bcast(radfrq,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iclobber,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(isfclyrm,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ied_grndvap,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)

   !---------------------------------------------------------------------------------------!
   !      We should only need the grid sizes, because we expect to import the coordinates  !
   ! and sizes to allocate our polygons.  The geometry is handled by BRAMS, but we want to !
   ! ensure that the variables are correctly set in the nodes should they be ever needed.  !
   !---------------------------------------------------------------------------------------!
   call MPI_Bcast(nnxp,maxgrds,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(nnyp,maxgrds,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)

   call MPI_Bcast(nzg,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(nzs,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)

   call MPI_Bcast(nslcon,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(isoilcol,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(slxclay,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(slxsand,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(slz,nzgmax,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(slmstr,nzgmax,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(stgoff,nzgmax,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ubmin,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ugbmin,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ustmin,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(zrough,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
  

   call MPI_Bcast(co2_offset,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)

   call MPI_Bcast(gamm,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(gamh,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(tprandtl,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ribmax,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(leaf_maxwhc,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)


   call MPI_Bcast(dt_census,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(yr1st_census,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(mon1st_census,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(min_recruit_dbh,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(idetailed,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(patch_keep,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)


   !---------------------------------------------------------------------------------------!
   !     These variables are useful to check for which output types to allocate.           !
   !---------------------------------------------------------------------------------------!
   call MPI_Bcast(writing_dail    ,1,MPI_LOGICAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(writing_mont    ,1,MPI_LOGICAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(writing_dcyc    ,1,MPI_LOGICAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(writing_year    ,1,MPI_LOGICAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(writing_long    ,1,MPI_LOGICAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(writing_eorq    ,1,MPI_LOGICAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(history_fast    ,1,MPI_LOGICAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(history_dail    ,1,MPI_LOGICAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(history_eorq    ,1,MPI_LOGICAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(fast_diagnostics,1,MPI_LOGICAL,mainnum,MPI_COMM_WORLD,ierr)
   !---------------------------------------------------------------------------------------!
#endif


   return
end subroutine masterput_ednl
!==========================================================================================!
!==========================================================================================!






!==========================================================================================!
!==========================================================================================!
subroutine nodeget_ednl(master_num)
   use ed_max_dims          , only : str_len                    & ! intent(out)
                                   , n_pft                      & ! intent(out)
                                   , maxpvars                   & ! intent(out)
                                   , nzgmax                     & ! intent(out)
                                   , str_len_short              & ! intent(out)
                                   , maxgrds                    & ! intent(out)
                                   , max_poi                    & ! intent(out)
                                   , max_ed_regions             & ! intent(out)
                                   , n_pft                      ! ! intent(out)
   use ed_misc_coms         , only : expnme                     & ! intent(out)
                                   , runtype                    & ! intent(out)
                                   , itimea                     & ! intent(out)
                                   , iyeara                     & ! intent(out)
                                   , imontha                    & ! intent(out)
                                   , idatea                     & ! intent(out)
                                   , itimez                     & ! intent(out)
                                   , iyearz                     & ! intent(out)
                                   , imonthz                    & ! intent(out)
                                   , idatez                     & ! intent(out)
                                   , dtlsm                      & ! intent(out)
                                   , radfrq                     & ! intent(out)
                                   , month_yrstep               & ! intent(out)
                                   , ifoutput                   & ! intent(out)
                                   , idoutput                   & ! intent(out)
                                   , imoutput                   & ! intent(out)
                                   , iqoutput                   & ! intent(out)
                                   , iyoutput                   & ! intent(out)
                                   , itoutput                   & ! intent(out)
                                   , iooutput                   & ! intent(out)
                                   , ndcycle                    & ! intent(out)
                                   , iclobber                   & ! intent(out)
                                   , obstime_db                 & ! intent(out)
                                   , frqfast                    & ! intent(out)
                                   , sfilin                     & ! intent(out)
                                   , ffilout                    & ! intent(out)
                                   , ied_init_mode              & ! intent(out)
                                   , thsums_database            & ! intent(out)
                                   , ivegt_dynamics             & ! intent(out)
                                   , ibigleaf                   & ! intent(out)
                                   , integration_scheme         & ! intent(out)
                                   , nsub_euler                 & ! intent(out)
                                   , end_time                   & ! intent(out)
                                   , current_time               & ! intent(out)
                                   , sfilout                    & ! intent(out)
                                   , frqstate                   & ! intent(out)
                                   , isoutput                   & ! intent(out)
                                   , iprintpolys                & ! intent(out)
                                   , printvars                  & ! intent(out)
                                   , npvars                     & ! intent(out)
                                   , pfmtstr                    & ! intent(out)
                                   , ipmin                      & ! intent(out)
                                   , ipmax                      & ! intent(out)
                                   , iedcnfgf                   & ! intent(out)
                                   , event_file                 & ! intent(out)
                                   , outfast                    & ! intent(out)
                                   , outstate                   & ! intent(out)
                                   , unitfast                   & ! intent(out)
                                   , unitstate                  & ! intent(out)
                                   , iadd_site_means            & ! intent(out)
                                   , iadd_patch_means           & ! intent(out)
                                   , iadd_cohort_means          & ! intent(out)
                                   , attach_metadata            & ! intent(out)
                                   , itimeh                     & ! intent(out)
                                   , iyearh                     & ! intent(out)
                                   , imonthh                    & ! intent(out)
                                   , idateh                     & ! intent(out)
                                   , iallom                     & ! intent(out)
                                   , economics_scheme           & ! intent(out)
                                   , igrass                     & ! intent(out)
                                   , min_site_area              & ! intent(out)
                                   , fast_diagnostics           & ! intent(out)
                                   , writing_dail               & ! intent(out)
                                   , writing_mont               & ! intent(out)
                                   , writing_dcyc               & ! intent(out)
                                   , writing_year               & ! intent(out)
                                   , writing_long               & ! intent(out) 
                                   , writing_eorq               & ! intent(out)
                                   , history_fast               & ! intent(out) 
                                   , history_dail               & ! intent(out) 
                                   , history_eorq               ! ! intent(out)
   use grid_coms            , only : nzg                        & ! intent(out)
                                   , nzs                        & ! intent(out)
                                   , ngrids                     & ! intent(out)
                                   , nnxp                       & ! intent(out)
                                   , nnyp                       & ! intent(out)
                                   , time                       & ! intent(out)
                                   , timmax                     ! ! intent(out)
   use soil_coms            , only : isoilflg                   & ! intent(out)
                                   , nslcon                     & ! intent(out)
                                   , isoilcol                   & ! intent(out)
                                   , slxclay                    & ! intent(out)
                                   , slxsand                    & ! intent(out)
                                   , slz                        & ! intent(out)
                                   , slmstr                     & ! intent(out)
                                   , stgoff                     & ! intent(out)
                                   , veg_database               & ! intent(out)
                                   , soil_database              & ! intent(out)
                                   , slcol_database             & ! intent(out)
                                   , soilstate_db               & ! intent(out)
                                   , soildepth_db               & ! intent(out)
                                   , isoilstateinit             & ! intent(out)
                                   , isoildepthflg              & ! intent(out)
                                   , isoilbc                    & ! intent(out)
                                   , sldrain                    & ! intent(out)
                                   , runoff_time                & ! intent(out)
                                   , zrough                     ! ! intent(out)
   use met_driver_coms      , only : lapse_scheme               & ! intent(out)
                                   , imetrad                    ! ! intent(out)
   use mem_polygons         , only : edres                      & ! intent(out)
                                   , maxsite                    & ! intent(out)
                                   , maxpatch                   & ! intent(out)
                                   , maxcohort                  ! ! intent(out)
   use physiology_coms      , only : iphysiol                   & ! intent(out)
                                   , h2o_plant_lim              & ! intent(out)
                                   , plant_hydro_scheme         & ! intent(out)
                                   , istomata_scheme            & ! intent(out)
                                   , istruct_growth_scheme      & ! intent(out)
                                   , istem_respiration_scheme   & ! intent(out)
                                   , trait_plasticity_scheme    & ! intent(out)
                                   , iddmort_scheme             & ! intent(out)
                                   , cbr_scheme                 & ! intent(out)
                                   , ddmort_const               & ! intent(out)
                                   , carbon_mortality_scheme    & ! intent(out)
                                   , hydraulic_mortality_scheme & ! intent(out)
                                   , n_plant_lim                & ! intent(out)
                                   , vmfact_c3                  & ! intent(out)
                                   , vmfact_c4                  & ! intent(out)
                                   , mphoto_trc3                & ! intent(out)
                                   , mphoto_tec3                & ! intent(out)
                                   , mphoto_c4                  & ! intent(out)
                                   , bphoto_blc3                & ! intent(out)
                                   , bphoto_nlc3                & ! intent(out)
                                   , bphoto_c4                  & ! intent(out)
                                   , kw_grass                   & ! intent(out)
                                   , kw_tree                    & ! intent(out)
                                   , gamma_c3                   & ! intent(out)
                                   , gamma_c4                   & ! intent(out)
                                   , d0_grass                   & ! intent(out)
                                   , d0_tree                    & ! intent(out)
                                   , alpha_c3                   & ! intent(out)
                                   , alpha_c4                   & ! intent(out)
                                   , klowco2in                  & ! intent(out)
                                   , rrffact                    & ! intent(out)
                                   , growthresp                 & ! intent(out)
                                   , quantum_efficiency_t       & ! intent(out)
                                   , q10_c3                     & ! intent(out)
                                   , q10_c4                     ! ! intent(out)
   use phenology_coms       , only : iphen_scheme               & ! intent(out)
                                   , repro_scheme               & ! intent(out)
                                   , iphenys1                   & ! intent(out)
                                   , iphenysf                   & ! intent(out)
                                   , iphenyf1                   & ! intent(out)
                                   , iphenyff                   & ! intent(out)
                                   , phenpath                   & ! intent(out)
                                   , radint                     & ! intent(out)
                                   , radslp                     & ! intent(out)
                                   , thetacrit                  ! ! intent(out)
   use decomp_coms          , only : n_decomp_lim               & ! intent(out)
                                   , decomp_scheme              ! ! intent(out)
   use pft_coms             , only : include_these_pft          & ! intent(out)
                                   , pasture_stock              & ! intent(out)
                                   , agri_stock                 & ! intent(out)
                                   , plantation_stock           & ! intent(out)
                                   , pft_1st_check              ! ! intent(out)
   use disturb_coms         , only : include_fire               & ! intent(out)
                                   , fire_parameter             & ! intent(out)
                                   , ianth_disturb              & ! intent(out)
                                   , sl_scale                   & ! intent(out)
                                   , sl_yr_first                & ! intent(out)
                                   , sl_nyrs                    & ! intent(out)
                                   , sl_pft                     & ! intent(out)
                                   , sl_prob_harvest            & ! intent(out)
                                   , sl_mindbh_harvest          & ! intent(out)
                                   , sl_biomass_harvest         & ! intent(out)
                                   , sl_skid_rel_area           & ! intent(out)
                                   , sl_skid_s_gtharv           & ! intent(out)
                                   , sl_skid_s_ltharv           & ! intent(out)
                                   , sl_felling_s_ltharv        & ! intent(out)
                                   , cl_fseeds_harvest          & ! intent(out)
                                   , cl_fstorage_harvest        & ! intent(out)
                                   , cl_fleaf_harvest           & ! intent(out)
                                   , lu_database                & ! intent(out)
                                   , plantation_file            & ! intent(out)
                                   , lu_rescale_file            & ! intent(out)
                                   , treefall_disturbance_rate  & ! intent(out)
                                   , time2canopy                & ! intent(out)
                                   , sm_fire                    & ! intent(out)
                                   , min_patch_area             ! ! intent(out)
   use optimiz_coms         , only : ioptinpt                   ! ! intent(out)
   use canopy_layer_coms    , only : crown_mod                  ! ! intent(out)
   use canopy_radiation_coms, only : icanrad                    & ! intent(out)
                                   , ihrzrad                    & ! intent(out)
                                   , ltrans_vis                 & ! intent(out)
                                   , ltrans_nir                 & ! intent(out)
                                   , lreflect_vis               & ! intent(out)
                                   , lreflect_nir               & ! intent(out)
                                   , orient_tree                & ! intent(out)
                                   , orient_grass               & ! intent(out)
                                   , clump_tree                 & ! intent(out)
                                   , clump_grass                ! ! intent(out)
   use rk4_coms             , only : rk4_tolerance              & ! intent(out)
                                   , ibranch_thermo             & ! intent(out)
                                   , ipercol                    ! ! intent(out)
   use canopy_air_coms      , only : icanturb                   & ! intent(out)
                                   , isfclyrm                   & ! intent(out)
                                   , ied_grndvap                & ! intent(out)
                                   , ubmin                      & ! intent(out)
                                   , ugbmin                     & ! intent(out)
                                   , ustmin                     & ! intent(out)
                                   , gamm                       & ! intent(out)
                                   , gamh                       & ! intent(out)
                                   , tprandtl                   & ! intent(out)
                                   , ribmax                     & ! intent(out)
                                   , lwidth_grass               & ! intent(out)
                                   , lwidth_bltree              & ! intent(out)
                                   , lwidth_nltree              & ! intent(out)
                                   , leaf_maxwhc                ! ! intent(out)
   use mem_edcp             , only : co2_offset                 ! ! intent(out)
   use detailed_coms        , only : dt_census                  & ! intent(out)
                                   , yr1st_census               & ! intent(out)
                                   , mon1st_census              & ! intent(out)
                                   , min_recruit_dbh            & ! intent(out)
                                   , idetailed                  & ! intent(out)
                                   , patch_keep                 ! ! intent(out)
   use fusion_fission_coms  , only : ifusion                    ! ! intent(out)
   implicit none
   !----- Standard common blocks. ---------------------------------------------------------!
#if defined(RAMS_MPI)
   include 'mpif.h'
#endif
   !----- Arguments. ----------------------------------------------------------------------!
   integer, intent(in) :: master_num
   !----- Local variables. ----------------------------------------------------------------!
   integer             :: ierr
   integer             :: npv
   integer             :: ng
   !---------------------------------------------------------------------------------------!


#if defined(RAMS_MPI)
   call MPI_Bcast(time,1,MPI_DOUBLE_PRECISION,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(timmax,1,MPI_DOUBLE_PRECISION,master_num,MPI_COMM_WORLD,ierr)

   call MPI_Bcast(current_time%year,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(current_time%month,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(current_time%date,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(current_time%time,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(current_time%ifirst,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)

   call MPI_Bcast(end_time%year,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(end_time%month,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(end_time%date,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(end_time%time,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(end_time%ifirst,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)

   call MPI_Bcast(dtlsm,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(month_yrstep,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ifoutput,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(idoutput,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(imoutput,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iqoutput,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iyoutput,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(itoutput,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iooutput,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(isoutput,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ndcycle,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iadd_site_means  ,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iadd_patch_means ,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iadd_cohort_means,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(attach_metadata,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(outfast,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(outstate,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(unitfast,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(unitstate,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ffilout,str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(sfilout,str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ied_init_mode,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(edres,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)

   do ng=1,maxgrds
      call MPI_Bcast(sfilin         (ng),str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)
      call MPI_Bcast(veg_database   (ng),str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)
      call MPI_Bcast(soil_database  (ng),str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)
      call MPI_Bcast(slcol_database (ng),str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)
      call MPI_Bcast(lu_database    (ng),str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)
      call MPI_Bcast(plantation_file(ng),str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)
      call MPI_Bcast(lu_rescale_file(ng),str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)
   end do

   call MPI_Bcast(thsums_database,str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(soilstate_db   ,str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(soildepth_db   ,str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(obstime_db     ,str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)

   call MPI_Bcast(isoilstateinit,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(isoildepthflg,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(isoilbc,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(sldrain,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ivegt_dynamics,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ibigleaf,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(integration_scheme,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(nsub_euler,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(rk4_tolerance,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ibranch_thermo,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iphysiol,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iallom,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(economics_scheme,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(igrass,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iphen_scheme,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(radint,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(radslp,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(repro_scheme,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(lapse_scheme,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(crown_mod,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(icanrad,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ihrzrad,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ltrans_vis,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ltrans_nir,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(lreflect_vis,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(lreflect_nir,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(orient_tree,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(orient_grass,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(clump_tree,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(clump_grass,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(decomp_scheme,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(h2o_plant_lim,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(plant_hydro_scheme,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(istomata_scheme,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(istruct_growth_scheme,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(istem_respiration_scheme,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(trait_plasticity_scheme,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iddmort_scheme,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(cbr_scheme,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ddmort_const,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(carbon_mortality_scheme,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(hydraulic_mortality_scheme,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(vmfact_c3,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(vmfact_c4,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(mphoto_trc3,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(mphoto_tec3,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(mphoto_c4,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(bphoto_blc3,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(bphoto_nlc3,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(bphoto_c4,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(kw_grass,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(kw_tree,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(gamma_c3,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(gamma_c4,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(d0_grass,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(d0_tree,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(alpha_c3,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(alpha_c4,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(klowco2in,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(rrffact,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(growthresp,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(lwidth_grass,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(lwidth_bltree,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(lwidth_nltree,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(q10_c3,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(q10_c4,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(thetacrit,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(quantum_efficiency_t,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(n_plant_lim,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(n_decomp_lim,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(include_fire,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(fire_parameter,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(sm_fire,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ianth_disturb,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(sl_scale           ,    1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(sl_yr_first        ,    1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(sl_nyrs            ,    1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(sl_pft             ,n_pft,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(sl_prob_harvest    ,n_pft,MPI_REAL   ,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(sl_mindbh_harvest  ,n_pft,MPI_REAL   ,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(sl_biomass_harvest ,    1,MPI_REAL   ,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(sl_skid_rel_area   ,    1,MPI_REAL   ,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(sl_skid_s_gtharv   ,    1,MPI_REAL   ,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(sl_skid_s_ltharv   ,    1,MPI_REAL   ,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(sl_felling_s_ltharv,    1,MPI_REAL   ,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(cl_fseeds_harvest  ,    1,MPI_REAL   ,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(cl_fstorage_harvest,    1,MPI_REAL   ,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(cl_fleaf_harvest   ,    1,MPI_REAL   ,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(icanturb,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ipercol,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(include_these_pft,n_pft,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(pasture_stock,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(agri_stock,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(plantation_stock,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(pft_1st_check,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ifusion,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(maxsite,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(maxpatch,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(maxcohort,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(min_site_area,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(min_patch_area,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(treefall_disturbance_rate,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(time2canopy,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(runoff_time,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iprintpolys,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(npvars,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   do npv=1,npvars
      call MPI_Bcast(printvars(npv),str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)
      call MPI_Bcast(pfmtstr(npv),str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)
   end do
   call MPI_Bcast(ipmin,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ipmax,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(imetrad ,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iphenys1,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iphenysf,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iphenyf1,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iphenyff,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iedcnfgf,str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(event_file,str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(phenpath,str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)

   !---------------------------------------------------------------------------------------!
   !      These are ED2 variables that have the same function as certain BRAMS namelist    !
   ! variables under a different name.                                                     !
   !---------------------------------------------------------------------------------------!
  
   call MPI_Bcast(frqfast,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(frqstate,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
  
   call MPI_Bcast(expnme,str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ngrids,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(runtype,str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(itimez,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(idatez,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(imonthz,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iyearz,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(itimeh,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(idateh,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(imonthh,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iyearh,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(itimea,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(idatea,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(imontha,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iyeara,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)

   call MPI_Bcast(radfrq,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iclobber,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(isfclyrm,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ied_grndvap,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)

   !---------------------------------------------------------------------------------------!
   !      We should only need the grid sizes, because we expect to import the coordinates  !
   ! and sizes to allocate our polygons.  The geometry is handled by BRAMS, but we want to !
   ! ensure that the variables are correctly set in the nodes should they be ever needed.  !
   !---------------------------------------------------------------------------------------!
   call MPI_Bcast(nnxp,maxgrds,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(nnyp,maxgrds,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)

   call MPI_Bcast(nzg,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(nzs,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)

   call MPI_Bcast(nslcon,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(isoilcol,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(slxclay,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(slxsand,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(slz,nzgmax,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(slmstr,nzgmax,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(stgoff,nzgmax,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ubmin,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ugbmin,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ustmin,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(zrough,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
  

   call MPI_Bcast(co2_offset,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)

   call MPI_Bcast(gamm,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(gamh,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(tprandtl,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ribmax,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(leaf_maxwhc,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)

   call MPI_Bcast(dt_census,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(yr1st_census,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(mon1st_census,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(min_recruit_dbh,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(idetailed,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(patch_keep,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)


   !---------------------------------------------------------------------------------------!
   !     These variables are useful to check for which output types to allocate.           !
   !---------------------------------------------------------------------------------------!
   call MPI_Bcast(writing_dail    ,1,MPI_LOGICAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(writing_mont    ,1,MPI_LOGICAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(writing_dcyc    ,1,MPI_LOGICAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(writing_year    ,1,MPI_LOGICAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(writing_long    ,1,MPI_LOGICAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(writing_eorq    ,1,MPI_LOGICAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(history_fast    ,1,MPI_LOGICAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(history_dail    ,1,MPI_LOGICAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(history_eorq    ,1,MPI_LOGICAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(fast_diagnostics,1,MPI_LOGICAL,master_num,MPI_COMM_WORLD,ierr)
   !---------------------------------------------------------------------------------------!
#endif

   return
end subroutine nodeget_ednl
!==========================================================================================!
!==========================================================================================!
