!==========================================================================================!
!==========================================================================================!
!     This subroutine will send the namelist information to the slave nodes.               !
!------------------------------------------------------------------------------------------!
subroutine masterput_ednl(mainnum)
   use ed_max_dims          , only : str_len                    & ! intent(in)
                                   , n_pft                      & ! intent(in)
                                   , maxpvars                   & ! intent(in)
                                   , nzgmax                     & ! intent(in)
                                   , str_len_short              & ! intent(in)
                                   , maxgrds                    & ! intent(in)
                                   , max_poi                    & ! intent(in)
                                   , max_ed_regions             & ! intent(in)
                                   , n_pft                      ! ! intent(in)
   use ed_misc_coms         , only : expnme                     & ! intent(in)
                                   , runtype                    & ! intent(in)
                                   , itimea                     & ! intent(in)
                                   , iyeara                     & ! intent(in)
                                   , imontha                    & ! intent(in)
                                   , idatea                     & ! intent(in)
                                   , itimez                     & ! intent(in)
                                   , iyearz                     & ! intent(in)
                                   , imonthz                    & ! intent(in)
                                   , idatez                     & ! intent(in)
                                   , dtlsm                      & ! intent(in)
                                   , radfrq                     & ! intent(in)
                                   , ifoutput                   & ! intent(in)
                                   , idoutput                   & ! intent(in)
                                   , imoutput                   & ! intent(in)
                                   , iqoutput                   & ! intent(in)
                                   , iyoutput                   & ! intent(in)
                                   , itoutput                   & ! intent(in)
                                   , ndcycle                    & ! intent(in)
                                   , iclobber                   & ! intent(in)
                                   , frqfast                    & ! intent(in)
                                   , sfilin                     & ! intent(in)
                                   , ffilout                    & ! intent(in)
                                   , ied_init_mode              & ! intent(in)
                                   , thsums_database            & ! intent(in)
                                   , ivegt_dynamics             & ! intent(in)
                                   , integration_scheme         & ! intent(in)
                                   , end_time                   & ! intent(in)
                                   , current_time               & ! intent(in)
                                   , sfilout                    & ! intent(in)
                                   , frqstate                   & ! intent(in)
                                   , isoutput                   & ! intent(in)
                                   , iprintpolys                & ! intent(in)
                                   , printvars                  & ! intent(in)
                                   , npvars                     & ! intent(in)
                                   , pfmtstr                    & ! intent(in)
                                   , ipmin                      & ! intent(in)
                                   , ipmax                      & ! intent(in)
                                   , iedcnfgf                   & ! intent(in)
                                   , event_file                 & ! intent(in)
                                   , outfast                    & ! intent(in)
                                   , outstate                   & ! intent(in)
                                   , unitfast                   & ! intent(in)
                                   , unitstate                  & ! intent(in)
                                   , attach_metadata            & ! intent(in)
                                   , itimeh                     & ! intent(in)
                                   , iyearh                     & ! intent(in)
                                   , imonthh                    & ! intent(in)
                                   , idateh                     & ! intent(in)
                                   , iallom                     & ! intent(in)
                                   , min_site_area              ! ! intent(in)
   use grid_coms            , only : nzg                        & ! intent(in)
                                   , nzs                        & ! intent(in)
                                   , ngrids                     & ! intent(in)
                                   , nnxp                       & ! intent(in)
                                   , nnyp                       & ! intent(in)
                                   , time                       & ! intent(in)
                                   , timmax                     ! ! intent(in)
   use soil_coms            , only : isoilflg                   & ! intent(in)
                                   , nslcon                     & ! intent(in)
                                   , isoilcol                   & ! intent(in)
                                   , slxclay                    & ! intent(in)
                                   , slxsand                    & ! intent(in)
                                   , slz                        & ! intent(in)
                                   , slmstr                     & ! intent(in)
                                   , stgoff                     & ! intent(in)
                                   , veg_database               & ! intent(in)
                                   , soil_database              & ! intent(in)
                                   , soilstate_db               & ! intent(in)
                                   , soildepth_db               & ! intent(in)
                                   , isoilstateinit             & ! intent(in)
                                   , isoildepthflg              & ! intent(in)
                                   , isoilbc                    & ! intent(in)
                                   , runoff_time                & ! intent(in)
                                   , zrough                     ! ! intent(in)
   use met_driver_coms      , only : lapse_scheme               & ! intent(in)
                                   , imetrad                    ! ! intent(in)
   use mem_polygons         , only : edres                      & ! intent(in)
                                   , maxsite                    & ! intent(in)
                                   , maxpatch                   & ! intent(in)
                                   , maxcohort                  ! ! intent(in)
   use physiology_coms      , only : iphysiol                   & ! intent(in)
                                   , h2o_plant_lim              & ! intent(in)
                                   , n_plant_lim                & ! intent(in)
                                   , vmfact                     & ! intent(in)
                                   , mfact                      & ! intent(in)
                                   , kfact                      & ! intent(in)
                                   , gamfact                    & ! intent(in)
                                   , d0fact                     & ! intent(in)
                                   , alphafact                  & ! intent(in)
                                   , rrffact                    & ! intent(in)
                                   , growthresp                 & ! intent(in)
                                   , quantum_efficiency_t       ! ! intent(in)
   use phenology_coms       , only : iphen_scheme               & ! intent(in)
                                   , repro_scheme               & ! intent(in)
                                   , iphenys1                   & ! intent(in)
                                   , iphenysf                   & ! intent(in)
                                   , iphenyf1                   & ! intent(in)
                                   , iphenyff                   & ! intent(in)
                                   , phenpath                   & ! intent(in)
                                   , radint                     & ! intent(in)
                                   , radslp                     & ! intent(in)
                                   , thetacrit                  ! ! intent(in)
   use decomp_coms          , only : n_decomp_lim               & ! intent(in)
                                   , LloydTaylor                ! ! intent(in)
   use pft_coms             , only : include_these_pft          & ! intent(in)
                                   , agri_stock                 & ! intent(in)
                                   , plantation_stock           & ! intent(in)
                                   , pft_1st_check              ! ! intent(in)
   use disturb_coms         , only : include_fire               & ! intent(in)
                                   , ianth_disturb              & ! intent(in)
                                   , lu_database                & ! intent(in)
                                   , plantation_file            & ! intent(in)
                                   , lu_rescale_file            & ! intent(in)
                                   , treefall_disturbance_rate  & ! intent(in)
                                   , time2canopy                & ! intent(in)
                                   , sm_fire                    ! ! intent(in)
   use optimiz_coms         , only : ioptinpt                   ! ! intent(in)
   use canopy_layer_coms    , only : crown_mod                  ! ! intent(in)
   use canopy_radiation_coms, only : icanrad                    & ! intent(in)
                                   , ltrans_vis                 & ! intent(in)
                                   , ltrans_nir                 & ! intent(in)
                                   , lreflect_vis               & ! intent(in)
                                   , lreflect_nir               & ! intent(in)
                                   , orient_tree                & ! intent(in)
                                   , orient_grass               & ! intent(in)
                                   , clump_tree                 & ! intent(in)
                                   , clump_grass                ! ! intent(in)
   use rk4_coms             , only : rk4_tolerance              & ! intent(in)
                                   , ibranch_thermo             & ! intent(in)
                                   , ipercol                    ! ! intent(in)
   use canopy_air_coms      , only : icanturb                   & ! intent(in)
                                   , isfclyrm                   & ! intent(in)
                                   , ied_grndvap                & ! intent(in)
                                   , ubmin                      & ! intent(in)
                                   , ugbmin                     & ! intent(in)
                                   , ustmin                     & ! intent(in)
                                   , gamm                       & ! intent(in) 
                                   , gamh                       & ! intent(in) 
                                   , tprandtl                   & ! intent(in)
                                   , ribmax                     & ! intent(in)
                                   , leaf_maxwhc                ! ! intent(in)
   use mem_edcp             , only : co2_offset                 ! ! intent(in)
   implicit none
   !----- Standard common blocks. ---------------------------------------------------------!
   include 'mpif.h'
   !----- Arguments. ----------------------------------------------------------------------!
   integer, intent(in) :: mainnum
   !----- Local variables. ----------------------------------------------------------------!
   integer             :: ierr
   integer             :: npv
   integer             :: ng
   !---------------------------------------------------------------------------------------!

   call MPI_Bcast(time,1,MPI_DOUBLE_PRECISION,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(timmax,1,MPI_DOUBLE_PRECISION,mainnum,MPI_COMM_WORLD,ierr)

   call MPI_Bcast(current_time%year,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(current_time%month,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(current_time%date,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(current_time%time,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(current_time%ifirst,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)

   call MPI_Bcast(end_time%year,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(end_time%month,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(end_time%date,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(end_time%time,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(end_time%ifirst,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)

   call MPI_Bcast(dtlsm,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ifoutput,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(idoutput,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(imoutput,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iqoutput,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iyoutput,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(itoutput,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(isoutput,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ndcycle,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(attach_metadata,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(outfast,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(outstate,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(unitfast,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(unitstate,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ffilout,str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(sfilout,str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ied_init_mode,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(edres,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)

   do ng=1,maxgrds
      call MPI_Bcast(sfilin         (ng),str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)
      call MPI_Bcast(veg_database   (ng),str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)
      call MPI_Bcast(soil_database  (ng),str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)
      call MPI_Bcast(lu_database    (ng),str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)
      call MPI_Bcast(plantation_file(ng),str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)
      call MPI_Bcast(lu_rescale_file(ng),str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)
   end do

   call MPI_Bcast(thsums_database,str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(soilstate_db   ,str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(soildepth_db   ,str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)

   call MPI_Bcast(isoilstateinit,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(isoildepthflg,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(isoilbc,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ivegt_dynamics,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(integration_scheme,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(rk4_tolerance,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ibranch_thermo,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iphysiol,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iallom,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iphen_scheme,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(radint,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(radslp,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(repro_scheme,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(lapse_scheme,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(crown_mod,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(icanrad,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ltrans_vis,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ltrans_nir,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(lreflect_vis,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(lreflect_nir,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(orient_tree,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(orient_grass,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(clump_tree,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(clump_grass,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(LloydTaylor,1,MPI_LOGICAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(h2o_plant_lim,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(vmfact,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(mfact,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(kfact,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(gamfact,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(d0fact,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(alphafact,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(rrffact,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(growthresp,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(thetacrit,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(quantum_efficiency_t,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(n_plant_lim,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(n_decomp_lim,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(include_fire,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(sm_fire,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ianth_disturb,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(icanturb,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ipercol,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(include_these_pft,n_pft,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(agri_stock,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(plantation_stock,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(pft_1st_check,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(maxsite,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(maxpatch,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(maxcohort,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(min_site_area,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(treefall_disturbance_rate,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(time2canopy,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(runoff_time,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iprintpolys,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(npvars,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   do npv=1,npvars
      call MPI_Bcast(printvars(npv),str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)
      call MPI_Bcast(pfmtstr(npv),str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)
   end do
   call MPI_Bcast(ipmin,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ipmax,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(imetrad ,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iphenys1,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iphenysf,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iphenyf1,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iphenyff,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iedcnfgf,str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(event_file,str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(phenpath,str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)

   !---------------------------------------------------------------------------------------!
   !      These are ED2 variables that have the same function as certain BRAMS namelist    !
   ! variables under a different name.                                                     !
   !---------------------------------------------------------------------------------------!
  
   call MPI_Bcast(frqfast,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(frqstate,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
  
   call MPI_Bcast(expnme,str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ngrids,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(runtype,str_len,MPI_CHARACTER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(itimez,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(idatez,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(imonthz,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iyearz,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(itimeh,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(idateh,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(imonthh,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iyearh,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(itimea,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(idatea,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(imontha,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iyeara,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)

   call MPI_Bcast(radfrq,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iclobber,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(isfclyrm,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ied_grndvap,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)

   !---------------------------------------------------------------------------------------!
   !      We should only need the grid sizes, because we expect to import the coordinates  !
   ! and sizes to allocate our polygons.  The geometry is handled by BRAMS, but we want to !
   ! ensure that the variables are correctly set in the nodes should they be ever needed.  !
   !---------------------------------------------------------------------------------------!
   call MPI_Bcast(nnxp,maxgrds,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(nnyp,maxgrds,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)

   call MPI_Bcast(nzg,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(nzs,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)

   call MPI_Bcast(nslcon,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(isoilcol,1,MPI_INTEGER,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(slxclay,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(slxsand,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(slz,nzgmax,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(slmstr,nzgmax,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(stgoff,nzgmax,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ubmin,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ugbmin,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ustmin,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(zrough,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
  

   call MPI_Bcast(co2_offset,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)

   call MPI_Bcast(gamm,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(gamh,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(tprandtl,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ribmax,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(leaf_maxwhc,1,MPI_REAL,mainnum,MPI_COMM_WORLD,ierr)

   return
end subroutine masterput_ednl
!==========================================================================================!
!==========================================================================================!






!==========================================================================================!
!==========================================================================================!
subroutine nodeget_ednl(master_num)
   use ed_max_dims          , only : str_len                    & ! intent(out)
                                   , n_pft                      & ! intent(out)
                                   , maxpvars                   & ! intent(out)
                                   , nzgmax                     & ! intent(out)
                                   , str_len_short              & ! intent(out)
                                   , maxgrds                    & ! intent(out)
                                   , max_poi                    & ! intent(out)
                                   , max_ed_regions             & ! intent(out)
                                   , n_pft                      ! ! intent(out)
   use ed_misc_coms         , only : expnme                     & ! intent(out)
                                   , runtype                    & ! intent(out)
                                   , itimea                     & ! intent(out)
                                   , iyeara                     & ! intent(out)
                                   , imontha                    & ! intent(out)
                                   , idatea                     & ! intent(out)
                                   , itimez                     & ! intent(out)
                                   , iyearz                     & ! intent(out)
                                   , imonthz                    & ! intent(out)
                                   , idatez                     & ! intent(out)
                                   , dtlsm                      & ! intent(out)
                                   , radfrq                     & ! intent(out)
                                   , ifoutput                   & ! intent(out)
                                   , idoutput                   & ! intent(out)
                                   , imoutput                   & ! intent(out)
                                   , iqoutput                   & ! intent(out)
                                   , iyoutput                   & ! intent(out)
                                   , itoutput                   & ! intent(out)
                                   , ndcycle                    & ! intent(out)
                                   , iclobber                   & ! intent(out)
                                   , frqfast                    & ! intent(out)
                                   , sfilin                     & ! intent(out)
                                   , ffilout                    & ! intent(out)
                                   , ied_init_mode              & ! intent(out)
                                   , thsums_database            & ! intent(out)
                                   , ivegt_dynamics             & ! intent(out)
                                   , integration_scheme         & ! intent(out)
                                   , end_time                   & ! intent(out)
                                   , current_time               & ! intent(out)
                                   , sfilout                    & ! intent(out)
                                   , frqstate                   & ! intent(out)
                                   , isoutput                   & ! intent(out)
                                   , iprintpolys                & ! intent(out)
                                   , printvars                  & ! intent(out)
                                   , npvars                     & ! intent(out)
                                   , pfmtstr                    & ! intent(out)
                                   , ipmin                      & ! intent(out)
                                   , ipmax                      & ! intent(out)
                                   , iedcnfgf                   & ! intent(out)
                                   , event_file                 & ! intent(out)
                                   , outfast                    & ! intent(out)
                                   , outstate                   & ! intent(out)
                                   , unitfast                   & ! intent(out)
                                   , unitstate                  & ! intent(out)
                                   , attach_metadata            & ! intent(out)
                                   , itimeh                     & ! intent(out)
                                   , iyearh                     & ! intent(out)
                                   , imonthh                    & ! intent(out)
                                   , idateh                     & ! intent(out)
                                   , iallom                     & ! intent(out)
                                   , min_site_area              ! ! intent(out)
   use grid_coms            , only : nzg                        & ! intent(out)
                                   , nzs                        & ! intent(out)
                                   , ngrids                     & ! intent(out)
                                   , nnxp                       & ! intent(out)
                                   , nnyp                       & ! intent(out)
                                   , time                       & ! intent(out)
                                   , timmax                     ! ! intent(out)
   use soil_coms            , only : isoilflg                   & ! intent(out)
                                   , nslcon                     & ! intent(out)
                                   , isoilcol                   & ! intent(out)
                                   , slxclay                    & ! intent(out)
                                   , slxsand                    & ! intent(out)
                                   , slz                        & ! intent(out)
                                   , slmstr                     & ! intent(out)
                                   , stgoff                     & ! intent(out)
                                   , veg_database               & ! intent(out)
                                   , soil_database              & ! intent(out)
                                   , soilstate_db               & ! intent(out)
                                   , soildepth_db               & ! intent(out)
                                   , isoilstateinit             & ! intent(out)
                                   , isoildepthflg              & ! intent(out)
                                   , isoilbc                    & ! intent(out)
                                   , runoff_time                & ! intent(out)
                                   , zrough                     ! ! intent(out)
   use met_driver_coms      , only : lapse_scheme               & ! intent(out)
                                   , imetrad                    ! ! intent(out)
   use mem_polygons         , only : edres                      & ! intent(out)
                                   , maxsite                    & ! intent(out)
                                   , maxpatch                   & ! intent(out)
                                   , maxcohort                  ! ! intent(out)
   use physiology_coms      , only : iphysiol                   & ! intent(out)
                                   , h2o_plant_lim              & ! intent(out)
                                   , n_plant_lim                & ! intent(out)
                                   , vmfact                     & ! intent(out)
                                   , mfact                      & ! intent(out)
                                   , kfact                      & ! intent(out)
                                   , gamfact                    & ! intent(out)
                                   , d0fact                     & ! intent(out)
                                   , alphafact                  & ! intent(out)
                                   , rrffact                    & ! intent(out)
                                   , growthresp                 & ! intent(out)
                                   , quantum_efficiency_t       ! ! intent(out)
   use phenology_coms       , only : iphen_scheme               & ! intent(out)
                                   , repro_scheme               & ! intent(out)
                                   , iphenys1                   & ! intent(out)
                                   , iphenysf                   & ! intent(out)
                                   , iphenyf1                   & ! intent(out)
                                   , iphenyff                   & ! intent(out)
                                   , phenpath                   & ! intent(out)
                                   , radint                     & ! intent(out)
                                   , radslp                     & ! intent(out)
                                   , thetacrit                  ! ! intent(out)
   use decomp_coms          , only : n_decomp_lim               & ! intent(out)
                                   , LloydTaylor                ! ! intent(out)
   use pft_coms             , only : include_these_pft          & ! intent(out)
                                   , agri_stock                 & ! intent(out)
                                   , plantation_stock           & ! intent(out)
                                   , pft_1st_check              ! ! intent(out)
   use disturb_coms         , only : include_fire               & ! intent(out)
                                   , ianth_disturb              & ! intent(out)
                                   , lu_database                & ! intent(out)
                                   , plantation_file            & ! intent(out)
                                   , lu_rescale_file            & ! intent(out)
                                   , treefall_disturbance_rate  & ! intent(out)
                                   , time2canopy                & ! intent(out)
                                   , sm_fire                    ! ! intent(out)
   use optimiz_coms         , only : ioptinpt                   ! ! intent(out)
   use canopy_layer_coms    , only : crown_mod                  ! ! intent(out)
   use canopy_radiation_coms, only : icanrad                    & ! intent(out)
                                   , ltrans_vis                 & ! intent(out)
                                   , ltrans_nir                 & ! intent(out)
                                   , lreflect_vis               & ! intent(out)
                                   , lreflect_nir               & ! intent(out)
                                   , orient_tree                & ! intent(out)
                                   , orient_grass               & ! intent(out)
                                   , clump_tree                 & ! intent(out)
                                   , clump_grass                ! ! intent(out)
   use rk4_coms             , only : rk4_tolerance              & ! intent(out)
                                   , ibranch_thermo             & ! intent(out)
                                   , ipercol                    ! ! intent(out)
   use canopy_air_coms      , only : icanturb                   & ! intent(out)
                                   , isfclyrm                   & ! intent(out)
                                   , ied_grndvap                & ! intent(out)
                                   , ubmin                      & ! intent(out)
                                   , ugbmin                     & ! intent(out)
                                   , ustmin                     & ! intent(out)
                                   , gamm                       & ! intent(out)
                                   , gamh                       & ! intent(out)
                                   , tprandtl                   & ! intent(out)
                                   , ribmax                     & ! intent(out)
                                   , leaf_maxwhc                ! ! intent(out)
   use mem_edcp             , only : co2_offset                 ! ! intent(out)

   implicit none
   !----- Standard common blocks. ---------------------------------------------------------!
   include 'mpif.h'
   !----- Arguments. ----------------------------------------------------------------------!
   integer, intent(in) :: master_num
   !----- Local variables. ----------------------------------------------------------------!
   integer             :: ierr
   integer             :: npv
   integer             :: ng
   !---------------------------------------------------------------------------------------!



   call MPI_Bcast(time,1,MPI_DOUBLE_PRECISION,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(timmax,1,MPI_DOUBLE_PRECISION,master_num,MPI_COMM_WORLD,ierr)

   call MPI_Bcast(current_time%year,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(current_time%month,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(current_time%date,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(current_time%time,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(current_time%ifirst,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)

   call MPI_Bcast(end_time%year,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(end_time%month,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(end_time%date,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(end_time%time,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(end_time%ifirst,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)

   call MPI_Bcast(dtlsm,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ifoutput,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(idoutput,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(imoutput,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iqoutput,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iyoutput,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(itoutput,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(isoutput,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ndcycle,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(attach_metadata,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(outfast,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(outstate,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(unitfast,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(unitstate,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ffilout,str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(sfilout,str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ied_init_mode,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(edres,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)

   do ng=1,maxgrds
      call MPI_Bcast(sfilin         (ng),str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)
      call MPI_Bcast(veg_database   (ng),str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)
      call MPI_Bcast(soil_database  (ng),str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)
      call MPI_Bcast(lu_database    (ng),str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)
      call MPI_Bcast(plantation_file(ng),str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)
      call MPI_Bcast(lu_rescale_file(ng),str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)
   end do

   call MPI_Bcast(thsums_database,str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(soilstate_db   ,str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(soildepth_db   ,str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)

   call MPI_Bcast(isoilstateinit,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(isoildepthflg,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(isoilbc,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ivegt_dynamics,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(integration_scheme,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(rk4_tolerance,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ibranch_thermo,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iphysiol,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iallom,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iphen_scheme,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(radint,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(radslp,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(repro_scheme,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(lapse_scheme,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(crown_mod,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(icanrad,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ltrans_vis,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ltrans_nir,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(lreflect_vis,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(lreflect_nir,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(orient_tree,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(orient_grass,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(clump_tree,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(clump_grass,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(LloydTaylor,1,MPI_LOGICAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(h2o_plant_lim,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(vmfact,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(mfact,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(kfact,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(gamfact,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(d0fact,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(alphafact,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(rrffact,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(growthresp,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(thetacrit,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(quantum_efficiency_t,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(n_plant_lim,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(n_decomp_lim,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(include_fire,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(sm_fire,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ianth_disturb,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(icanturb,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ipercol,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(include_these_pft,n_pft,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(agri_stock,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(plantation_stock,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(pft_1st_check,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(maxsite,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(maxpatch,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(maxcohort,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(min_site_area,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(treefall_disturbance_rate,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(time2canopy,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(runoff_time,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iprintpolys,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(npvars,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   do npv=1,npvars
      call MPI_Bcast(printvars(npv),str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)
      call MPI_Bcast(pfmtstr(npv),str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)
   end do
   call MPI_Bcast(ipmin,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ipmax,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(imetrad ,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iphenys1,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iphenysf,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iphenyf1,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iphenyff,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iedcnfgf,str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(event_file,str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(phenpath,str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)

   !---------------------------------------------------------------------------------------!
   !      These are ED2 variables that have the same function as certain BRAMS namelist    !
   ! variables under a different name.                                                     !
   !---------------------------------------------------------------------------------------!
  
   call MPI_Bcast(frqfast,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(frqstate,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
  
   call MPI_Bcast(expnme,str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ngrids,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(runtype,str_len,MPI_CHARACTER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(itimez,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(idatez,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(imonthz,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iyearz,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(itimeh,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(idateh,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(imonthh,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iyearh,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(itimea,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(idatea,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(imontha,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iyeara,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)

   call MPI_Bcast(radfrq,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(iclobber,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(isfclyrm,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ied_grndvap,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)

   !---------------------------------------------------------------------------------------!
   !      We should only need the grid sizes, because we expect to import the coordinates  !
   ! and sizes to allocate our polygons.  The geometry is handled by BRAMS, but we want to !
   ! ensure that the variables are correctly set in the nodes should they be ever needed.  !
   !---------------------------------------------------------------------------------------!
   call MPI_Bcast(nnxp,maxgrds,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(nnyp,maxgrds,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)

   call MPI_Bcast(nzg,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(nzs,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)

   call MPI_Bcast(nslcon,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(isoilcol,1,MPI_INTEGER,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(slxclay,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(slxsand,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(slz,nzgmax,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(slmstr,nzgmax,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(stgoff,nzgmax,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ubmin,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ugbmin,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ustmin,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(zrough,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
  

   call MPI_Bcast(co2_offset,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)

   call MPI_Bcast(gamm,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(gamh,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(tprandtl,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(ribmax,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)
   call MPI_Bcast(leaf_maxwhc,1,MPI_REAL,master_num,MPI_COMM_WORLD,ierr)

   return
end subroutine nodeget_ednl
!==========================================================================================!
!==========================================================================================!
